class WPFDistributionModel{
  String anx_id, comp_id, anx_year, anx_statement, anx_received, anx_financial, anx_net_profit,
      anx_allocated, anx_count_cat1, anx_count_cat2, anx_count_cat3, anx_workers, anx_amount_1,
      anx_amount_2, anx_amount_3, anx_dispense_1, anx_dispense_2, anx_dispense_3, anx_dispensed,
      anx_transfered, anx_mode, anx_number, anx_proof, anx_bank, anx_payment, anx_paid_at,
      anx_percent, anx_employees, anx_medium, created_at;

  WPFDistributionModel(
      this.anx_id,
      this.comp_id,
      this.anx_year,
      this.anx_statement,
      this.anx_received,
      this.anx_financial,
      this.anx_net_profit,
      this.anx_allocated,
      this.anx_count_cat1,
      this.anx_count_cat2,
      this.anx_count_cat3,
      this.anx_workers,
      this.anx_amount_1,
      this.anx_amount_2,
      this.anx_amount_3,
      this.anx_dispense_1,
      this.anx_dispense_2,
      this.anx_dispense_3,
      this.anx_dispensed,
      this.anx_transfered,
      this.anx_mode,
      this.anx_number,
      this.anx_proof,
      this.anx_bank,
      this.anx_payment,
      this.anx_paid_at,
      this.anx_percent,
      this.anx_employees,
      this.anx_medium,
      this.created_at);
}